name: build

on:
  push:
    paths-ignore:
      - 'go2index/**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install
    
    - run: npm run build
    
    - name: Commit
      run: |
        git config --global user.email GithubAction@email.com
        git config --global user.name GithubActionBot
        git add .
        git commit -m "update dist" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        branch: ${{ github.ref }}
